version: "3.9"
services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    restart: always
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - distributed_web
  # works on linux platform only
  db-store:
    image: mariadb:latest
    restart: always
    environment:
     - MARIADB_ROOT_PASSWORD:mariarootPass1@
    networks:
     - distributed_web
    volumes:
     - /var/lib/mysql:/var/lib/mysql
  # works on linux platform only
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    - ZOO_LOG_LEVEL=OFF
    networks:
    - distributed_web 
  # works on linux platform only
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
    - '9092:9092'
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
    networks:
     - distributed_web
  web-node-one:
    build: 
     context: .
     dockerfile: Web.NodeOne/Docker/Dockerfile    
    ports:
     - "44352:44352"
    networks:
     - distributed_web
    depends_on:
     - dotnet
     - db-store
  web-node-two:
    build: 
     context: .
     dockerfile: Web.NodeTwo/Docker/Dockerfile
    ports:
     - "5001:5001"
    networks:
     - distributed_web
    depends_on:
     - dotnet
     - kafka     
  web-node-three:
    build: 
     context: .
     dockerfile: Web.NodeThree/Docker/Dockerfile
    ports:
     - "5003:5003"
    networks:
     - distributed_web
    depends_on:
     - dotnet
     - kafka
networks:
 distributed_web:
