version: "3.9"
services:
 dotnet:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    restart: always
 jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - distributed-web-example
  # works on linux platform only
  db-store:
    image: mariadb:latest
    restart: always
    environment:
    ROOT_PASSWORD: secret_password
    networks:
     - distributed-web-example
  # works on linux platform only
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    ports:
     - '2181:2181'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes     
  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
    - '9092:9092'
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
  web-node-one:
    build: .\Web.NodeOne\
    restart: always
    ports:
     - "44352:44352"
    networks:
     - distributed-web-example
    depends_on:
     - dotnet
     - db-store
  web-node-two:
    build: .\Web.NodeTwo\
    restart: always
    ports:
     - "5001:5001"
    networks:
     - distributed-web-example
    depends_on:
     - dotnet
     - kafka     
  web-node-three:
    build: .\Web.NodeThree\
    restart: always
    ports:
     - "5003:5003"
    networks:
     - distributed-web-example
    depends_on:
     - dotnet
     - kafka
